### 
GET http://localhost:3003/users/

### 
POST http://localhost:3003/users/add/
Content-Type: application/json

{
    "id":"1",
    "username":"Nandakumar"
}

### 
DELETE http://localhost:3003/users/3/

### 
POST http://localhost:3003/tasks/add/
Content-Type: application/json

{
    "id":"1",
    "user_id":"1",
    "task":"learn full stack devlopment",
    "is_completed":"false"
}

### 
DELETE http://localhost:3003/task/1/

### 
GET http://localhost:3003/task/user/2/

### 
PUT  http://localhost:3003/task/update/1/
Content-Type: application/json

{
    "is_completed":"false"
}

###

GET http://localhost:3003/username/2/